## [0.0.2](https://github.com/IBM/data-virtualization-on-cloud-python-sdk/compare/v0.0.1...v0.0.2) (2021-08-16)


### Bug Fixes

* **build:** prepare build for first deployment ([#13](https://github.com/IBM/data-virtualization-on-cloud-python-sdk/issues/13)) ([5a58f05](https://github.com/IBM/data-virtualization-on-cloud-python-sdk/commit/5a58f0595357c0f679eb0f59c6593b346dadf41a))
* **tox.ini:** try to fix error: py37-lint: commands failed ([47292ab](https://github.com/IBM/data-virtualization-on-cloud-python-sdk/commit/47292abedecca7d140ffae17b971edcc63e2926e))
* add .pylintrc file ([a91061a](https://github.com/IBM/data-virtualization-on-cloud-python-sdk/commit/a91061a9acf63a1b41eb36d8bd1f184ea078a326))
